// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, Subtodo, SubtodoView, find, from, ref, template,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('janus'), DomView = ref.DomView, template = ref.template, find = ref.find, from = ref.from;

  $ = require('jquery');

  Subtodo = require('../model/subtodo').Subtodo;

  SubtodoView = (function(superClass) {
    extend(SubtodoView, superClass);

    function SubtodoView() {
      return SubtodoView.__super__.constructor.apply(this, arguments);
    }

    SubtodoView._dom = function() {
      return $('<div class="subtodo"> <div class="subtodoCheck"></div> <div class="subtodoName"></div> </div>');
    };

    SubtodoView._template = template(find('.subtodo').classed('done', from('done')), find('.subtodoCheck').render(from.attribute('done')).context('edit'), find('.subtodoName').render(from.attribute('name')).context('edit').options({
      placeholder: '(new subitem)'
    }));

    return SubtodoView;

  })(DomView);

  module.exports = {
    SubtodoView: SubtodoView,
    registerWith: function(library) {
      return library.register(Subtodo, SubtodoView);
    }
  };

}).call(this);
