// Generated by CoffeeScript 1.11.1
(function() {
  var $, DomView, Todo, TodoList, TodoListSummaryView, TodoListView, blank, find, from, ref, template, textOrElse,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  $ = require('jquery');

  ref = require('janus'), DomView = ref.DomView, template = ref.template, find = ref.find, from = ref.from;

  TodoList = require('../model/todo-list').TodoList;

  Todo = require('../model/todo').Todo;

  blank = function(x) {
    return (x == null) || x === '';
  };

  textOrElse = function(fallback) {
    return function(x) {
      if (blank(x)) {
        return fallback;
      } else {
        return x;
      }
    };
  };

  TodoListSummaryView = (function(superClass) {
    extend(TodoListSummaryView, superClass);

    function TodoListSummaryView() {
      return TodoListSummaryView.__super__.constructor.apply(this, arguments);
    }

    TodoListSummaryView._dom = function() {
      return $('<div class="todoListSummary"> <div class="name"></div> <div class="completion"> <span class="completed"></span>/<span class="total"></span> completed </div> </div>');
    };

    TodoListSummaryView._template = template(find('.name').text(from('name').map(textOrElse('(untitled list)'))), find('.completion .completed').text(from('todos').map(function(list) {
      return list.filter(function(todo) {
        return todo.watch('done');
      }).watchLength();
    })), find('.completion .total').text(from('todos').map(function(list) {
      return list.watchLength();
    })));

    return TodoListSummaryView;

  })(DomView);

  TodoListView = (function(superClass) {
    extend(TodoListView, superClass);

    function TodoListView() {
      return TodoListView.__super__.constructor.apply(this, arguments);
    }

    TodoListView._dom = function() {
      return $('<div class="todoList"> <div class="todoList-titleWrapper"> <span class="todoList-titleField"></span> <span class="todoList-titleGhost"></span> </div> <div class="todos"></div> <div class="toolbar"> <button class="addTodo">New</button> </div> </div>');
    };

    TodoListView._template = template(find('.todoList-titleField').render(from.attribute('name')).context('edit'), find('.todoList-titleGhost').text(from('name').map(textOrElse('(untitled list)'))), find('.todos').render(from('todos')));

    TodoListView.prototype._wireEvents = function() {
      var dom;
      dom = this.artifact();
      return dom.find('button.addTodo').on('click', (function(_this) {
        return function() {
          return _this.subject.get('todos').add(new Todo());
        };
      })(this));
    };

    return TodoListView;

  })(DomView);

  module.exports = {
    TodoListSummaryView: TodoListSummaryView,
    registerWith: function(library) {
      library.register(TodoList, TodoListSummaryView, {
        context: 'summary'
      });
      return library.register(TodoList, TodoListView);
    }
  };

}).call(this);
