// Generated by CoffeeScript 1.11.1
(function() {
  var List, Model, Subtodo, Subtodos, attribute, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('janus'), Model = ref.Model, attribute = ref.attribute, List = ref.List;

  Subtodo = (function(superClass) {
    extend(Subtodo, superClass);

    function Subtodo() {
      return Subtodo.__super__.constructor.apply(this, arguments);
    }

    Subtodo.attribute('name', attribute.TextAttribute);

    Subtodo.attribute('done', attribute.BooleanAttribute);

    return Subtodo;

  })(Model);

  Subtodos = (function(superClass) {
    extend(Subtodos, superClass);

    function Subtodos() {
      return Subtodos.__super__.constructor.apply(this, arguments);
    }

    Subtodos.modelClass = Subtodo;

    return Subtodos;

  })(List);

  module.exports = {
    Subtodo: Subtodo,
    Subtodos: Subtodos
  };

}).call(this);
