// Generated by CoffeeScript 1.11.1
(function() {
  var List, Model, TodoList, TodoLists, Todos, attribute, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('janus'), Model = ref.Model, attribute = ref.attribute, List = ref.List;

  Todos = require('./todo').Todos;

  TodoList = (function(superClass) {
    extend(TodoList, superClass);

    function TodoList() {
      return TodoList.__super__.constructor.apply(this, arguments);
    }

    TodoList.attribute('name', attribute.TextAttribute);

    TodoList.attribute('todos', (function(superClass1) {
      extend(_Class, superClass1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.collectionClass = Todos;

      _Class.prototype["default"] = function() {
        return new Todos();
      };

      _Class.prototype.writeDefault = true;

      return _Class;

    })(attribute.CollectionAttribute));

    return TodoList;

  })(Model);

  TodoLists = (function(superClass) {
    extend(TodoLists, superClass);

    function TodoLists() {
      return TodoLists.__super__.constructor.apply(this, arguments);
    }

    TodoLists.modelClass = TodoList;

    return TodoLists;

  })(List);

  module.exports = {
    TodoList: TodoList,
    TodoLists: TodoLists
  };

}).call(this);
