// Generated by CoffeeScript 1.11.1
(function() {
  var BrowserWindow, app, hWnd, path, ref, url;

  ref = require('electron'), app = ref.app, BrowserWindow = ref.BrowserWindow;

  path = require('path');

  url = require('url');

  hWnd = null;

  app.on('ready', function() {
    hWnd = new BrowserWindow({
      width: 650,
      height: 480
    });
    hWnd.loadURL(url.format({
      pathname: path.join(__dirname, 'app.html'),
      protocol: 'file:',
      slashes: true
    }));
    hWnd.on('closed', function() {
      return hWnd = null;
    });
    return hWnd.on('window-all-closed', function() {
      return app.quit();
    });
  });

}).call(this);
