// Generated by CoffeeScript 1.11.1
(function() {
  var BrowserWindow, app, ref;

  ref = require('electron'), app = ref.app, BrowserWindow = ref.BrowserWindow;

  app.on('ready', function() {
    var hWnd;
    hWnd = new BrowserWindow({
      width: 650,
      height: 480
    });
    hWnd.on('closed', function() {
      return hWnd = null;
    });
    return hWnd.on('window-all-closed', function() {
      return app.quit();
    });
  });

}).call(this);
