// Generated by CoffeeScript 1.11.1
(function() {
  var $, App, Library, Main, app, ref, stdlib, views;

  $ = require('jquery');

  window.jQuery = window.$ = $;

  ref = require('janus').application, App = ref.App, Library = ref.Library;

  stdlib = require('janus-stdlib');

  Main = require('./viewmodel/main').Main;

  views = new Library();

  stdlib.view.registerWith(views);

  require('./view/main').registerWith(views);

  require('./view/todo-list').registerWith(views);

  require('./view/todo').registerWith(views);

  require('./view/subtodo').registerWith(views);

  app = new App({
    views: views
  });

  $(function() {
    var main, mainView;
    main = new Main();
    mainView = app.getView(main);
    $('#janus').append(mainView.artifact());
    return mainView.wireEvents();
  });

}).call(this);
