// Generated by CoffeeScript 1.11.1
(function() {
  var List, Main, Model, TodoLists, attribute, ref,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('janus'), Model = ref.Model, attribute = ref.attribute, List = ref.List;

  TodoLists = require('../model/todo-list').TodoLists;

  Main = (function(superClass) {
    extend(Main, superClass);

    function Main() {
      return Main.__super__.constructor.apply(this, arguments);
    }

    Main.attribute('todoLists', (function(superClass1) {
      extend(_Class, superClass1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.collectionClass = TodoLists;

      _Class.prototype["default"] = function() {
        return new TodoLists();
      };

      _Class.prototype.writeDefault = true;

      return _Class;

    })(attribute.CollectionAttribute));

    Main.attribute('current', (function(superClass1) {
      extend(_Class, superClass1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.values = function() {
        return this.model.watch('todoLists');
      };

      _Class.prototype.transient = true;

      return _Class;

    })(attribute.EnumAttribute));

    return Main;

  })(Model);

  module.exports = {
    Main: Main
  };

}).call(this);
